### ISSUE TITLE
Ng-select causes errors in the UI when scrolling through the component

### ISSUE THREAD

**Issue by yhegen** [SoftwareAG/cumulocity-asset-viewer-widget#2]
I used this widget outside the application builder to integrate it permanently into my cockpit.

However, I recognized when using the configuration tab to edit the widget, scrolling results in strange behavior in the UI.

Example: Before scrolling
![image](https://user-images.githubusercontent.com/45969355/155135785-76be41ae-16e0-455e-99f6-07ee8473b2da.png)

Example: After scrolling
![image](https://user-images.githubusercontent.com/45969355/155135960-a118b8a2-61fe-4d6f-b7a9-ce937ab799c1.png)

**Comment by yhegen** [comment]
I could fix this when removing the "appendTo" fragment inside the ng-select HTML. I would appreciate it if you could verify if the "appendTo" is really needed, or solve the error in another way.

**Comment by SheethalJR** [comment]
This issue has now been fixed along with the new enhancements.
Hence, closing the issue.
