### ISSUE TITLE
custom fragments support

### ISSUE THREAD

**Issue by janhumble** [SoftwareAG/cumulocity-asset-viewer-widget#4]
The asset viewer widget needs to better accommodate custom fragments.  Since the asset viewer widget is our primary cockpit "asset table" replacement that supports device drill-downs we need to enhance the "list" view to better accommodate list cases.  So 2 feature enhancements:
1. Ability to include arbitrary number of custom fragments (currently only supports one) or at least a good number (e.g. 20)
2. Ability to lock the widget to just a list or grid view - primarily to recoup some of the real estate taken up by the selector.

**Comment by janhumble** [comment]
We need also to change the name of "Grid View" to either "List" or "Table" view.  The current name doesn't make sense and is causing confusion with customers.

**Comment by SheethalJR** [comment]
Enhancements have been implemented and released. 
Hence, closing the issue.
